### get books list
GET http://localhost:5148/api/books
Accept: application/json

### get book by id
GET http://localhost:5148/api/books/2
Accept: application/json

### create a new book
POST http://localhost:5148/api/books
Content-Type: application/json

{
    "title": "C# Minimal APIs",
    "author": "John Doe",
    "pages": 320,
    "price": 29.99,
    "description": "Un libro sobre Minimal APIs en .NET."
}

### update a book
PUT http://localhost:5148/api/books
Content-Type: application/json

{
    "id": 1,
    "title": "C# Minimal APIs - Segunda Edición",
    "author": "John Doe",
    "pages": 350,
    "price": 34.99,
    "description": "Actualización del libro sobre Minimal APIs en .NET."
}

### delete a book
DELETE http://localhost:5148/api/books/1
